global NET, PERFORMANCE_STATISTICS, CRITERION, BEST_ACC, METRICS, ADAS, \
    CHECKPOINT_PATH, EARLY_STOP, CONFIG
NET = None
PERFORMANCE_STATISTICS = None
CRITERION = None
BEST_ACC = 0
METRICS = None
ADAS = None
CHECKPOINT_PATH = None
EARLY_STOP = None
CONFIG = None
